name: GCP deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/892056173251/locations/global/workloadIdentityPools/identity-pool-example/providers/github-provider'
        service_account: 'c3po-585@plucky-day-459020-j8.iam.gserviceaccount.com'
      
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - run: gcloud app deploy
